---
language: ruby
sudo: true
cache: bundler
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: ["bundle exec rake syntax", "bundle exec rake lint", "bundle exec rake spec SPEC_OPTS='--format documentation'", "bundle exec rake metadata_lint", "bundle exec rake rubocop"]
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="ubuntu-1404"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="centos-6"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="centos-7"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
notifications:
  email: true
